footer
Oxana200/commit-and-pray pull request #1
Opened 2024-11-15 17:58 UTC by karina-lgtm

2024-11-15 18:13 UTC, Oxana200 commented
У своєму файлі не прописуємо нічого крім розмітки футера, загальна розмітка уже прописана

2024-11-15 18:15 UTC, Oxana200 requested changes

2024-11-15 18:15 UTC, Oxana200 commented on src/partials/footer.html
> +
У своєму файлі не прописуємо нічого крім розмітки футера, загальна розмітка уже прописана

2024-11-18 14:12 UTC, Oxana200 requested changes

2024-11-18 14:12 UTC, Oxana200 commented on src/css/footer.css
> +.footer-nav-list {
До навігації додаємо ховер та фокус, реалізовуємо крапку через афтер як в хедері, тільки хай вона буде білою, як іконки при ховері

2024-11-18 14:12 UTC, Oxana200 commented on src/partials/footer.html
> +                  <svg class="footer-social-icon" width="18" height="18">
Вирішіть проблему з іконками.

2024-11-18 14:24 UTC, karina-lgtm commented
Дякую, але я не знаю як виправити проблему з іконками. Тому як що це
можливо, потрібна допомога ментора)


Пн, 18 нояб. 2024 г. в 15:12, Oksana Moisiuk ***@***.***>:

> ***@***.**** requested changes on this pull request.
> ------------------------------
>
> In src/css/footer.css
> <https://github.com/Oxana200/commit-and-pray/pull/1#discussion_r1846656583>
> :
>
> > +        font-size: 28px;
> +        line-height: 1.14;
> +        max-width: 524px;
> +        margin-bottom:100px
> +    }
> +}
> +
> ***@***.*** only screen and (min-width: 1280px) {
> +    .footer-text {
> +        position: absolute;
> +        top: 90px;
> +        right:367px
> +    }
> +}
> +
> +.footer-nav-list {
>
> До навігації додаємо ховер та фокус, реалізовуємо крапку через афтер як в
> хедері, тільки хай вона буде білою, як іконки при ховері
> ------------------------------
>
> In src/partials/footer.html
> <https://github.com/Oxana200/commit-and-pray/pull/1#discussion_r1846657432>
> :
>
> > @@ -0,0 +1,83 @@
> +<footer class="end-page" id="footer">
> +    <div class="footer-container container">
> +      <div class="footer-content">
> +        <div class="footer-row">
> +          <div class="footer-logo-link">
> +            <a href="" class="footer-logo">watchcharm</a>
> +            <ul class="footer-socials-list">
> +              <li class="footer-socials">
> +                <a
> +                  href="https://www.facebook.com/goITclub/"
> +                  class="footer-social-link"
> +                  target="_blank"
> +                >
> +                  <svg class="footer-social-icon" width="18" height="18">
>
> Вирішіть проблему з іконками.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/Oxana200/commit-and-pray/pull/1#pullrequestreview-2442739758>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/BLQZ5ICVF5ZSFSIRFZRSRCT2BHYWXAVCNFSM6AAAAABR3V2SOWVHI2DSMVQWIX3LMV43YUDVNRWFEZLROVSXG5CSMV3GSZLXHMZDINBSG4ZTSNZVHA>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2024-11-18 19:25 UTC, closed without merging