Reviews section
Oxana200/commit-and-pray pull request #4
Opened 2024-11-16 16:33 UTC by Artem-Pivtorak

2024-11-16 19:28 UTC, dmitriyabis commented on src/css/reviews.css
> +    padding-bottom: 40px;
Зміни на margin

2024-11-16 19:29 UTC, dmitriyabis commented on src/css/reviews.css
> +    padding-left: 65px;
Цей padding не потрібен, його дію виконує контейнер

2024-11-16 19:33 UTC, dmitriyabis commented on src/css/reviews.css
> +    margin: 0 20px;
Цей margin не потрібен

2024-11-16 19:34 UTC, dmitriyabis commented on src/css/reviews.css
> +}
Сюди треба додати властивість gap:16;

2024-11-16 19:37 UTC, dmitriyabis commented
Будь ласка, виправ помилки та додай адаптив

2024-11-16 19:40 UTC, dmitriyabis reviewed
Додав коментарі до деяких рядків коду

2024-11-18 13:59 UTC, Oxana200 requested changes

2024-11-18 13:59 UTC, Oxana200 commented on src/css/reviews.css
> +@media (min-width: 375px) and (max-width: 767px) {
Ми не прописуємо медіа правило для мобільної верстки, так як працюємо за підходом mobile first

2024-11-18 13:59 UTC, Oxana200 commented on src/css/reviews.css
> +/* Базовий стан: всі коментарі видимі */
Всі ці коментарі не потрібні, коментуємо тільки необхідне та англійською.

2024-11-18 13:59 UTC, Oxana200 commented on src/partials/reviews.html
> +                srcset="../img/reviews/john-wax.jpg 1x, ../img/reviews/john-wax-2x.jpg 2x" alt="John Wax">
У всіх зображеннях після додавання прибираємо . у шляхах, інакше вони не відображатимуться на живій сторінці

2024-11-18 19:51 UTC, dmitriyabis reviewed
Виправ помилки

2024-11-19 10:04 UTC, Oxana200 requested changes
І ПРИБЕРІТЬ КРАПКИ У ШЛЯХАХ ДО ЗОБРАЖЕННЯ ІНАКШЕ ВОНИ НЕ ВІДОБРАЖАТИМУТЬСЯ НА ЖИВІЙ СТОРІНЦІ

2024-11-19 10:04 UTC, Oxana200 commented on src/css/reviews.css
> +    font-family: "Gilroy", sans-serif;
Остерігайтесь дублювання стилів, код має бути чийсти. Фонт фемілі вказані в загальних стилях, тож цього ніде не має бути. Також перевірте чи однакові стилі не повторюються у медіа правилах. Якщо стилі з мобілки збігають то у медіа правилах їх не треба дублювати.

2024-11-19 10:04 UTC, Oxana200 commented on src/css/reviews.css
> +
Всі стилі, які йдуть нижче мають бути у дужках у медіа правилі, тому шрифт заголовка у вас і не збігається з макетом. наступного разу перед тим як відправити коміт, перевіряйте те що вийшло у інструментах розробнила

2024-11-19 11:40 UTC, Oxana200 requested changes

2024-11-19 11:40 UTC, Oxana200 commented on src/css/reviews.css
> +
відцентруйте карточку рів'ю і для мобільної версії теж

2024-11-19 11:40 UTC, Oxana200 commented on src/partials/reviews.html
> +<section class="reviews-section">
Додайте секції айдішник за назвою секції

2024-11-19 13:57 UTC, Oxana200 approved these changes

2024-11-19 13:57 UTC, merged