chinazez
Oxana200/commit-and-pray pull request #8
Opened 2024-11-17 11:59 UTC by skolobaev13

2024-11-18 08:51 UTC, Oxana200 requested changes

2024-11-18 08:51 UTC, Oxana200 commented on src/css/header.css
> +.btn-menu {
Вам потрібно змінити фоновий колір, так як колір сайту не білий і кнопка має обводку
![image](https://github.com/user-attachments/assets/49e001f7-45b4-4852-84da-1bbd5bf7074e)

2024-11-18 08:51 UTC, Oxana200 commented on src/css/header.css
> +
Додайте кнопці якийсь ховер та фокус

2024-11-18 08:51 UTC, Oxana200 commented on src/css/header.css
> +  padding-top: 240px;
Зробіть його автоматичним, так як при перевірці вкінці не іидно іконок на соц мережі
![image](https://github.com/user-attachments/assets/313fe93a-b884-4a13-9f1b-37887f8d4c7c)

2024-11-18 08:51 UTC, Oxana200 commented on src/css/header.css
> +
Додайте кнопці якийсь ховер та фокус

2024-11-18 10:05 UTC, skolobaev13 commented
змінив

2024-11-18 20:15 UTC, dmitriyabis reviewed
Виправіть та додайте про те що каже Оксана, а також з макета в меню додайте в навігації кружечки (так як робили в комп'ютерній версії навігації)

2024-11-18 20:33 UTC, skolobaev13 commented
> Виправіть та додайте про те що каже Оксана, а також з макета в меню додайте в навігації кружечки (так як робили в комп'ютерній версії навігації)

бєк всюди стоїть такий як й макеті,в модальці є кружечки при ховері й фокусі

2024-11-19 09:45 UTC, Oxana200 approved these changes

2024-11-19 09:45 UTC, merged